import dotenv from "dotenv";
dotenv.config({ path: ".env.local" });

import express from "express";
import cors from "cors";
import multer from "multer";

const app = express();
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 20 * 1024 * 1024 } });

app.use(cors());
app.use(express.json({ limit: "50mb" }));

const GEMINI_KEY = process.env.GEMINI_API_KEY;
const GITHUB_TOKEN = process.env.GITHUB_TOKEN;
const githubHeaders = {
  Accept: "application/vnd.github.v3+json",
  "User-Agent": "PortfolioForge",
  ...(GITHUB_TOKEN ? { Authorization: `Bearer ${GITHUB_TOKEN}` } : {}),
};
// gemini-flash-lite-latest: fastest available model (~2s response)
const GEMINI_FAST_URL = `https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-lite-latest:generateContent?key=${GEMINI_KEY}`;
const GEMINI_URL = GEMINI_FAST_URL;

// ── helper: call Gemini with text only ────────────────────────────────────────
async function geminiText(prompt, url = GEMINI_URL, maxTokens = 4096) {
  const res = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      contents: [{ parts: [{ text: prompt }] }],
      generationConfig: {
        temperature: 0.1,
        maxOutputTokens: maxTokens,
      },
    }),
  });
  if (!res.ok) {
    const err = await res.text();
    throw new Error(`Gemini error ${res.status}: ${err.substring(0, 100)}`);
  }
  const data = await res.json();
  return data.candidates?.[0]?.content?.parts?.[0]?.text || "";
}

// ── helper: call Gemini with file + text ──────────────────────────────────────
async function geminiMultimodal(fileBase64, mimeType, prompt, url = GEMINI_FAST_URL) {
  const res = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      contents: [{
        parts: [
          { inlineData: { mimeType, data: fileBase64 } },
          { text: prompt },
        ],
      }],
      generationConfig: {
        temperature: 0.1,
        maxOutputTokens: 2048,
      },
    }),
  });
  if (!res.ok) {
    const err = await res.text();
    throw new Error(`Gemini error ${res.status}: ${err}`);
  }
  const data = await res.json();
  return data.candidates?.[0]?.content?.parts?.[0]?.text || "";
}

// ── AI markers for GitHub ─────────────────────────────────────────────────────
const AI_TOOL_MARKERS = ["lovable","bolt.new","v0.dev","cursor","windsurf","replit","created with lovable","built with bolt","generated by ai"];
const AI_FILE_PATTERNS = [".cursorrules",".bolt","lovable.config",".v0",".replit"];

async function checkForAIMarkers(username, repoName) {
  try {
    const readmeRes = await fetch(`https://api.github.com/repos/${username}/${repoName}/readme`, {
      headers: githubHeaders,
    });
    if (readmeRes.ok) {
      const d = await readmeRes.json();
      if (d.content) {
        const content = Buffer.from(d.content, "base64").toString("utf8").toLowerCase();
        for (const marker of AI_TOOL_MARKERS) if (content.includes(marker)) return true;
      }
    }
    const contentsRes = await fetch(`https://api.github.com/repos/${username}/${repoName}/contents`, {
      headers: githubHeaders,
    });
    if (contentsRes.ok) {
      const contents = await contentsRes.json();
      if (Array.isArray(contents))
        for (const file of contents)
          for (const pattern of AI_FILE_PATTERNS)
            if (file.name.toLowerCase().includes(pattern)) return true;
    }
  } catch { /* silent */ }
  return false;
}

// ══════════════════════════════════════════════════════════════════════════════
// POST /api/fetch-github
// ══════════════════════════════════════════════════════════════════════════════
app.post("/api/fetch-github", async (req, res) => {
  try {
    const { githubUrl } = req.body;
    if (!githubUrl) return res.status(400).json({ error: "Invalid GitHub URL" });

    const match = githubUrl.match(/github\.com\/([^\/\?#]+)/);
    if (!match) return res.status(400).json({ error: "Invalid GitHub URL" });
    const username = match[1];

    const [profileRes, reposRes, eventsRes] = await Promise.all([
      fetch(`https://api.github.com/users/${username}`, { headers: githubHeaders }),
      fetch(`https://api.github.com/users/${username}/repos?per_page=100&sort=pushed&direction=desc`, { headers: githubHeaders }),
      fetch(`https://api.github.com/users/${username}/events/public?per_page=100`, { headers: githubHeaders }),
    ]);

    if (!profileRes.ok) {
      const msg = profileRes.status === 403 ? "GitHub API rate limit exceeded." : profileRes.status === 404 ? `GitHub user not found: ${username}` : `GitHub API error: ${profileRes.status}`;
      return res.status(profileRes.status).json({ error: msg });
    }

    const profile = await profileRes.json();
    const repos = await reposRes.json();
    const events = await eventsRes.json();

    let pushCount = 0, prCount = 0;
    const collaborations = new Set();
    for (const event of events) {
      if (event.type === "PushEvent") pushCount++;
      if (event.type === "PullRequestEvent") prCount++;
      if (event.repo?.name && !event.repo.name.startsWith(`${username}/`)) collaborations.add(event.repo.name);
    }

    const languageCounts = {};
    let totalStars = 0, ownedRepos = 0, forkedRepos = 0;
    for (const repo of repos) {
      if (repo.language) languageCounts[repo.language] = (languageCounts[repo.language] || 0) + (repo.stargazers_count + 1);
      totalStars += repo.stargazers_count || 0;
      repo.fork ? forkedRepos++ : ownedRepos++;
    }
    const totalLangScore = Object.values(languageCounts).reduce((a, b) => a + b, 0);
    const topLanguages = Object.entries(languageCounts).sort((a, b) => b[1] - a[1]).slice(0, 6)
      .map(([name, score]) => ({ name, percentage: Math.round((score / totalLangScore) * 100) }));

    const topRepos = repos.filter((r) => !r.fork).slice(0, 6);
    const aiResults = await Promise.all(topRepos.map((r) => checkForAIMarkers(username, r.name)));
    const aiDetectedRepos = topRepos.filter((_, i) => aiResults[i]).map((r) => r.name);
    const topProjects = topRepos.map((r, i) => ({
      name: r.name, description: r.description || "No description provided",
      tech: [r.language].filter(Boolean), stars: r.stargazers_count,
      forks: r.forks_count || 0, link: r.html_url, isAiGenerated: aiResults[i], lastUpdated: r.pushed_at,
    }));

    const daysOnGithub = Math.floor((Date.now() - new Date(profile.created_at).getTime()) / 86400000);
    const eventDates = new Set(events.map((e) => new Date(e.created_at).toDateString()));
    const today = new Date();
    let streak = 0;
    for (let i = 0; i < 30; i++) {
      const d = new Date(today); d.setDate(d.getDate() - i);
      if (eventDates.has(d.toDateString())) streak++; else if (i > 0) break;
    }
    const recentCommitCount = events.filter((e) => e.type === "PushEvent")
      .reduce((sum, e) => sum + (e.payload?.commits?.length || 0), 0);

    return res.json({
      name: profile.name || username,
      title: profile.bio?.split(".")[0] || "Software Developer",
      bio: profile.bio || `Developer based in ${profile.location || "the world"}.`,
      avatar: profile.avatar_url, email: profile.email || `${username}@github.com`,
      location: profile.location || "Earth", github: githubUrl, linkedin: "",
      website: profile.blog || "",
      skills: [...new Set(repos.filter((r) => r.language).map((r) => r.language))].slice(0, 10),
      projects: topProjects, experience: [], education: [], volunteering: [],
      githubStats: {
        totalCommits: recentCommitCount > 0 ? recentCommitCount : profile.public_repos * 15,
        publicRepos: profile.public_repos, privateRepos: profile.total_private_repos || 0,
        ownedRepos, forkedRepos, followers: profile.followers, following: profile.following,
        totalStars, pullRequests: prCount, pushes: pushCount, daysOnGithub,
        recentCollaborations: [...collaborations].slice(0, 5),
        aiGeneratedContent: aiDetectedRepos.length, aiDetectedRepos, topLanguages,
        contributionStreak: streak, accountCreated: profile.created_at,
        lastActive: events[0]?.created_at || profile.updated_at,
      },
    });
  } catch (e) {
    console.error("fetch-github error:", e);
    return res.status(500).json({ error: e.message || "Unknown error" });
  }
});

// ══════════════════════════════════════════════════════════════════════════════
// POST /api/fetch-leetcode
// ══════════════════════════════════════════════════════════════════════════════
app.post("/api/fetch-leetcode", async (req, res) => {
  try {
    const { username } = req.body;
    if (!username) return res.status(400).json({ error: "Username is required" });

    const query = `{
      matchedUser(username: "${username}") {
        username
        submitStatsGlobal { acSubmissionNum { difficulty count } }
        profile { ranking }
      }
      userContestRanking(username: "${username}") { attendedContestsCount rating }
      recentAcSubmissionList(username: "${username}", limit: 5) { title }
    }`;

    const response = await fetch("https://leetcode.com/graphql", {
      method: "POST",
      headers: { "Content-Type": "application/json", Referer: "https://leetcode.com", "User-Agent": "PortfolioForge/1.0" },
      body: JSON.stringify({ query }),
    });

    if (!response.ok) return res.status(response.status).json({ error: `LeetCode API error: ${response.status}` });

    const data = await response.json();
    if (!data?.data?.matchedUser) return res.status(404).json({ error: `LeetCode user not found: ${username}` });

    const user = data.data.matchedUser;
    const contest = data.data.userContestRanking;
    const stats = user.submitStatsGlobal?.acSubmissionNum || [];
    const easySolved = stats.find((s) => s.difficulty === "Easy")?.count || 0;
    const mediumSolved = stats.find((s) => s.difficulty === "Medium")?.count || 0;
    const hardSolved = stats.find((s) => s.difficulty === "Hard")?.count || 0;
    const totalSolved = stats.find((s) => s.difficulty === "All")?.count || (easySolved + mediumSolved + hardSolved);

    return res.json({
      username: user.username, totalSolved, easySolved, mediumSolved, hardSolved,
      ranking: user.profile?.ranking || 0, acceptanceRate: 0,
      contestRating: Math.round(contest?.rating || 0), totalContests: contest?.attendedContestsCount || 0,
    });
  } catch (e) {
    console.error("fetch-leetcode error:", e);
    return res.status(500).json({ error: e.message || "Unknown error" });
  }
});

// ══════════════════════════════════════════════════════════════════════════════
// POST /api/parse-resume
// ══════════════════════════════════════════════════════════════════════════════
const RESUME_KEYWORDS = ["experience","education","skills","projects","work history","certifications","summary","objective","employment","university","college","degree","bachelor","master"];

app.post("/api/parse-resume", upload.single("resume"), async (req, res) => {
  try {
    if (!GEMINI_KEY) return res.status(500).json({ error: "AI service not configured" });
    if (!req.file) return res.status(400).json({ error: "No resume file provided" });

    let parsedGithub = {};
    try { parsedGithub = JSON.parse(req.body.githubData || "{}"); } catch {}

    const fileBuffer = req.file.buffer;
    const originalName = req.file.originalname?.toLowerCase() || "";
    let mimeType = req.file.mimetype;

    if (originalName.endsWith(".pdf")) mimeType = "application/pdf";
    else if (originalName.endsWith(".docx")) mimeType = "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
    else if (originalName.endsWith(".doc")) mimeType = "application/msword";
    else if (originalName.endsWith(".txt")) mimeType = "text/plain";

    // Validate txt files
    if (mimeType === "text/plain") {
      const textContent = fileBuffer.toString("utf8").toLowerCase();
      const hasKeywords = RESUME_KEYWORDS.some((k) => textContent.includes(k));
      if (!hasKeywords) return res.status(400).json({ error: "This doesn't appear to be a resume. Please upload your actual resume." });
    }

    const base64Content = fileBuffer.toString("base64");

    const textPrompt = `You are a resume parser. First, determine if this document is actually a resume/CV.

STEP 1 - VALIDATION:
If this is NOT a resume, respond ONLY with:
{"error": "not_a_resume", "reason": "Brief explanation"}

STEP 2 - If it IS a resume, extract structured information and merge with GitHub data.

GITHUB DATA (prefer resume for experience/education, prefer github for projects/skills):
${JSON.stringify(parsedGithub).substring(0, 3000)}

Return a JSON object with these exact fields:
{
  "name": "Full Name",
  "title": "Professional Title",
  "bio": "Short professional bio (1-2 sentences)",
  "email": "email@example.com",
  "phone": "phone/mobile number if found, else empty string",
  "location": "City, State",
  "linkedin": "linkedin url if found",
  "website": "personal website if found",
  "skills": ["skill1", "skill2", ...up to 12 skills],
  "experience": [{"company": "Company", "role": "Role Title", "period": "2020 - 2023", "description": "Brief description"}],
  "education": [{"institution": "University", "degree": "Degree Name", "period": "2016 - 2020"}],
  "volunteering": [{"org": "Organization", "role": "Role", "period": "2020 - Present", "description": "Brief description"}],
  "projects": [{"name": "Project", "description": "Description", "tech": ["Tech1"], "stars": 0, "link": "url"}]
}

IMPORTANT: Return ONLY valid JSON, no markdown, no explanation.`;

    let content;
    try {
      content = await geminiMultimodal(base64Content, mimeType, textPrompt);
    } catch (e) {
      console.error("Gemini multimodal error:", e.message);
      return res.status(503).json({ error: e.message });
    }

    content = content.replace(/```json\n?/g, "").replace(/```\n?/g, "").trim();

    let parsed;
    try { parsed = JSON.parse(content); }
    catch { return res.status(500).json({ error: "Failed to parse resume data" }); }

    if (parsed.error === "not_a_resume") return res.status(400).json({ error: `This doesn't appear to be a resume: ${parsed.reason}` });

    // Name validation
    const github = parsedGithub;
    if (parsed.name && github.name) {
      const clean = (s) => s.toLowerCase().replace(/[^a-z]/g, "");
      const githubWords = (github.name + " " + (github.github || "")).split(/[\s\/]+/).map(clean).filter((w) => w.length >= 3);
      const resumeWords = parsed.name.split(/\s+/).map(clean).filter((w) => w.length >= 3);
      const hasMatch = githubWords.some((gw) => resumeWords.some((rw) => gw === rw || gw.includes(rw) || rw.includes(gw)));
      if (!hasMatch) {
        return res.status(400).json({
          error: `Name mismatch: GitHub profile name "${github.name}" does not match resume name "${parsed.name}". Please ensure the resume belongs to the same person as the GitHub profile.`
        });
      }
    }

    return res.json({
      name: parsed.name || github.name || "Developer",
      title: parsed.title || github.title || "Software Developer",
      bio: parsed.bio || github.bio || "",
      avatar: github.avatar || "",
      email: parsed.email || github.email || "",
      phone: parsed.phone || "",
      location: parsed.location || github.location || "",
      github: github.github || "",
      linkedin: parsed.linkedin || github.linkedin || "",
      website: parsed.website || github.website || "",
      skills: parsed.skills?.length ? parsed.skills : github.skills || [],
      experience: parsed.experience?.length ? parsed.experience : github.experience || [],
      education: parsed.education?.length ? parsed.education : github.education || [],
      volunteering: parsed.volunteering?.length ? parsed.volunteering : github.volunteering || [],
      projects: parsed.projects?.length ? parsed.projects : github.projects || [],
      githubStats: github.githubStats || null,
    });
  } catch (e) {
    console.error("parse-resume error:", e);
    return res.status(500).json({ error: e.message || "Unknown error" });
  }
});

// ══════════════════════════════════════════════════════════════════════════════
// POST /api/analyze-candidate
// ══════════════════════════════════════════════════════════════════════════════
app.post("/api/analyze-candidate", async (req, res) => {
  try {
    if (!GEMINI_KEY) return res.status(500).json({ error: "AI service not configured" });
    const { portfolioData, requiredTechStack, experienceLevel } = req.body;
    if (!portfolioData) return res.status(400).json({ error: "No portfolio data provided" });

    // Trim portfolio data to reduce prompt size and speed up response
    const trimmed = {
      name: portfolioData.name, title: portfolioData.title, bio: portfolioData.bio,
      skills: portfolioData.skills?.slice(0, 15),
      experience: portfolioData.experience?.slice(0, 5),
      education: portfolioData.education?.slice(0, 3),
      projects: portfolioData.projects?.slice(0, 6).map((p) => ({
        name: p.name, description: p.description?.substring(0, 150),
        tech: p.tech?.slice(0, 6), stars: p.stars, isAiGenerated: p.isAiGenerated,
      })),
      githubStats: portfolioData.githubStats ? {
        totalCommits: portfolioData.githubStats.totalCommits,
        publicRepos: portfolioData.githubStats.publicRepos,
        followers: portfolioData.githubStats.followers,
        pullRequests: portfolioData.githubStats.pullRequests,
        contributionStreak: portfolioData.githubStats.contributionStreak,
        topLanguages: portfolioData.githubStats.topLanguages?.slice(0, 5),
        aiGeneratedContent: portfolioData.githubStats.aiGeneratedContent,
        daysOnGithub: portfolioData.githubStats.daysOnGithub,
      } : null,
      leetcodeStats: portfolioData.leetcodeStats,
    };

    const prompt = `You are an expert technical recruiter and ATS analyst. Analyze this candidate's profile and provide a hiring recommendation.

CANDIDATE DATA:
${JSON.stringify(trimmed)}

Analyze based on:
1. GitHub activity (commits, repos, languages, contributions, collaboration)
2. Technical skills breadth and depth
3. Work experience relevance and progression
4. Education background
5. Project quality and impact
6. Overall profile completeness
7. LeetCode performance (if available)
8. ATS Resume Analysis (keywords, format, skills match)
${requiredTechStack?.length ? `9. Required Tech Stack: ${requiredTechStack.join(", ")}. Include "techStackMatch" with matched/missing arrays.` : ""}
${experienceLevel ? `10. Experience Level Required: "${experienceLevel}". Include "experienceLevelMatch": { "required": "${experienceLevel}", "assessed": "level", "isMatch": true/false, "explanation": "..." }.` : ""}

If a project has "No description provided", infer what it likely does from its name and tech stack.

SCORING (0-100 overallScore):
- Below 50: "DO NOT CONSIDER"
- 50-60: "MILD CHANCE"
- 60-70: "MODERATE"
- 70-80: "AVERAGE"
- 80-90: "GOOD"
- 90-100: "EXCEPTIONAL"

Return ONLY valid compact JSON (no spaces/newlines, keep all text fields SHORT — max 15 words each):
{"overallScore":number,"verdict":"DO NOT CONSIDER|MILD CHANCE|MODERATE|AVERAGE|GOOD|EXCEPTIONAL","atsScore":{"overall":number,"keywordScore":number,"formatScore":number,"experienceScore":number,"educationScore":number,"skillsScore":number,"suggestions":["tip1","tip2"]},"summary":"1-2 sentence summary","strengths":["s1","s2","s3"],"concerns":["c1","c2"],"githubInsights":{"activityLevel":"short","codeQuality":"short","consistency":"short","collaboration":"short"},"leetcodeInsights":{"problemSolvingLevel":"short","difficultyBalance":"short","contestPerformance":"short","summary":"short"},"technicalAssessment":{"primaryStack":"stack","experienceLevel":"Junior/Mid/Senior/Staff","specializations":["a1"]},"inferredProjectDescriptions":{},"hiringNotes":"2 sentence max"}`;

    let content;
    try {
      console.log("[analyze] prompt chars:", prompt.length, "| sending to Gemini...");
      const t0 = Date.now();
      content = await geminiText(prompt, GEMINI_URL, 1500);
      console.log("[analyze] Gemini responded in", Date.now()-t0, "ms | content chars:", content.length);
    } catch (e) {
      console.error("Gemini analyze error:", e.message);
      return res.status(503).json({ error: e.message });
    }

    content = content.replace(/```json\n?/g, "").replace(/```\n?/g, "").trim();

    let parsed;
    try { parsed = JSON.parse(content); }
    catch { return res.status(500).json({ error: "Failed to parse analysis" }); }

    return res.json(parsed);
  } catch (e) {
    console.error("analyze-candidate error:", e);
    return res.status(500).json({ error: e.message || "Unknown error" });
  }
});

app.listen(4001, () => console.log("✅ API server running on http://localhost:4001"));
