import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

// Common AI tool markers to detect AI-built repositories
const AI_TOOL_MARKERS = [
  "lovable", "bolt.new", "v0.dev", "cursor", "windsurf", "replit",
  "created with lovable", "built with bolt", "generated by ai",
  "this project was bootstrapped with create-react-app", // common but check other signals
];

const AI_FILE_PATTERNS = [
  ".cursorrules", ".bolt", "lovable.config", ".v0", ".replit",
];

async function checkForAIMarkers(username: string, repoName: string): Promise<boolean> {
  try {
    // Check README for AI tool mentions
    const readmeRes = await fetch(
      `https://api.github.com/repos/${username}/${repoName}/readme`,
      { headers: { "Accept": "application/vnd.github.v3+json", "User-Agent": "PortfolioForge" } }
    );
    if (readmeRes.ok) {
      const readmeData = await readmeRes.json();
      if (readmeData.content) {
        const content = atob(readmeData.content).toLowerCase();
        for (const marker of AI_TOOL_MARKERS) {
          if (content.includes(marker.toLowerCase())) return true;
        }
      }
    }

    // Check root directory for AI config files
    const contentsRes = await fetch(
      `https://api.github.com/repos/${username}/${repoName}/contents`,
      { headers: { "Accept": "application/vnd.github.v3+json", "User-Agent": "PortfolioForge" } }
    );
    if (contentsRes.ok) {
      const contents = await contentsRes.json();
      if (Array.isArray(contents)) {
        for (const file of contents) {
          for (const pattern of AI_FILE_PATTERNS) {
            if (file.name.toLowerCase().includes(pattern.toLowerCase())) return true;
          }
        }
      }
    }
  } catch {
    // Silent fail - don't block if we can't check
  }
  return false;
}

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const { githubUrl } = await req.json();
    
    // Extract username from URL
    const match = githubUrl.match(/github\.com\/([^\/\?#]+)/);
    if (!match) {
      return new Response(JSON.stringify({ error: "Invalid GitHub URL" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }
    const username = match[1];

    // Fetch GitHub profile, repos, and events in parallel
    const [profileRes, reposRes, eventsRes] = await Promise.all([
      fetch(`https://api.github.com/users/${username}`, {
        headers: { "Accept": "application/vnd.github.v3+json", "User-Agent": "PortfolioForge" },
      }),
      fetch(`https://api.github.com/users/${username}/repos?per_page=100&sort=pushed&direction=desc`, {
        headers: { "Accept": "application/vnd.github.v3+json", "User-Agent": "PortfolioForge" },
      }),
      fetch(`https://api.github.com/users/${username}/events/public?per_page=100`, {
        headers: { "Accept": "application/vnd.github.v3+json", "User-Agent": "PortfolioForge" },
      }),
    ]);

    if (!profileRes.ok) {
      const errorBody = await profileRes.text();
      console.error(`GitHub API error for ${username}: ${profileRes.status} - ${errorBody}`);
      const errorMsg = profileRes.status === 403 
        ? "GitHub API rate limit exceeded. Please try again in a few minutes."
        : profileRes.status === 404 
          ? `GitHub user not found: ${username}`
          : `GitHub API error: ${profileRes.status}`;
      return new Response(JSON.stringify({ error: errorMsg }), {
        status: profileRes.status,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const profile = await profileRes.json();
    const repos = await reposRes.json();
    const events = await eventsRes.json();

    // Calculate accurate stats from events (last 90 days of activity)
    let pushCount = 0;
    let prCount = 0;
    let issueCount = 0;
    let reviewCount = 0;
    let forkCount = 0;
    let createCount = 0;
    const collaborations = new Set<string>();
    const commitMessages: string[] = [];
    
    for (const event of events) {
      switch (event.type) {
        case "PushEvent":
          pushCount++;
          // Get actual commit count from push events
          if (event.payload?.commits) {
            commitMessages.push(...event.payload.commits.map((c: any) => c.message));
          }
          break;
        case "PullRequestEvent":
          prCount++;
          break;
        case "IssuesEvent":
          issueCount++;
          break;
        case "PullRequestReviewEvent":
          reviewCount++;
          break;
        case "ForkEvent":
          forkCount++;
          break;
        case "CreateEvent":
          createCount++;
          break;
      }
      // Track collaborations
      if (event.repo?.name && !event.repo.name.startsWith(`${username}/`)) {
        collaborations.add(event.repo.name);
      }
    }

    // Calculate language stats from repos
    const languageCounts: Record<string, number> = {};
    let totalStars = 0;
    let totalForks = 0;
    let ownedRepos = 0;
    let forkedRepos = 0;
    
    for (const repo of repos) {
      if (repo.language) {
        languageCounts[repo.language] = (languageCounts[repo.language] || 0) + (repo.stargazers_count + 1);
      }
      totalStars += repo.stargazers_count || 0;
      totalForks += repo.forks_count || 0;
      if (repo.fork) {
        forkedRepos++;
      } else {
        ownedRepos++;
      }
    }
    
    const totalLangScore = Object.values(languageCounts).reduce((a, b) => a + b, 0);
    const topLanguages = Object.entries(languageCounts)
      .sort((a, b) => b[1] - a[1])
      .slice(0, 6)
      .map(([name, score]) => ({ name, percentage: Math.round((score / totalLangScore) * 100) }));

    // Check for AI-generated repos (check top 6 repos for efficiency)
    const topRepos = repos.filter((r: any) => !r.fork).slice(0, 6);
    const aiCheckPromises = topRepos.map((r: any) => checkForAIMarkers(username, r.name));
    const aiResults = await Promise.all(aiCheckPromises);
    
    // Map AI detection results to repo names
    const aiDetectedRepos: string[] = [];
    topRepos.forEach((repo: any, i: number) => {
      if (aiResults[i]) aiDetectedRepos.push(repo.name);
    });

    // Top projects (up to 6) with AI detection flag
    const topProjects = topRepos.map((r: any, i: number) => ({
      name: r.name,
      description: r.description || "No description provided",
      tech: [r.language].filter(Boolean),
      stars: r.stargazers_count,
      forks: r.forks_count || 0,
      link: r.html_url,
      isAiGenerated: aiResults[i],
      lastUpdated: r.pushed_at,
    }));

    // Days on GitHub
    const createdDate = new Date(profile.created_at);
    const daysOnGithub = Math.floor((Date.now() - createdDate.getTime()) / (1000 * 60 * 60 * 24));

    // Calculate contribution streak estimate from recent events
    const eventDates = new Set(events.map((e: any) => new Date(e.created_at).toDateString()));
    const today = new Date();
    let streak = 0;
    for (let i = 0; i < 30; i++) {
      const d = new Date(today);
      d.setDate(d.getDate() - i);
      if (eventDates.has(d.toDateString())) {
        streak++;
      } else if (i > 0) {
        break;
      }
    }

    // Calculate total commits from recent activity (more accurate)
    const recentCommitCount = events
      .filter((e: any) => e.type === "PushEvent")
      .reduce((sum: number, e: any) => sum + (e.payload?.commits?.length || 0), 0);

    const result = {
      name: profile.name || username,
      title: profile.bio?.split('.')[0] || "Software Developer",
      bio: profile.bio || `Developer based in ${profile.location || "the world"}. Check out my work on GitHub!`,
      avatar: profile.avatar_url,
      email: profile.email || `${username}@github.com`,
      location: profile.location || "Earth",
      github: githubUrl,
      linkedin: "",
      website: profile.blog || "",
      skills: [...new Set(repos.filter((r: any) => r.language).map((r: any) => r.language))].slice(0, 10),
      projects: topProjects,
      experience: [],
      education: [],
      volunteering: [],
      githubStats: {
        totalCommits: recentCommitCount > 0 ? recentCommitCount : profile.public_repos * 15, // Use events if available
        publicRepos: profile.public_repos,
        privateRepos: profile.total_private_repos || 0,
        ownedRepos,
        forkedRepos,
        followers: profile.followers,
        following: profile.following,
        totalStars,
        totalForks,
        pullRequests: prCount,
        pushes: pushCount,
        issues: issueCount,
        reviews: reviewCount,
        daysOnGithub,
        recentCollaborations: [...collaborations].slice(0, 5),
        aiGeneratedContent: aiDetectedRepos.length,
        aiDetectedRepos,
        topLanguages,
        contributionStreak: streak,
        accountCreated: profile.created_at,
        lastActive: events[0]?.created_at || profile.updated_at,
      },
    };

    return new Response(JSON.stringify(result), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (e) {
    console.error("fetch-github error:", e);
    return new Response(JSON.stringify({ error: e instanceof Error ? e.message : "Unknown error" }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
