const AI_TOOL_MARKERS = ["lovable","bolt.new","v0.dev","cursor","windsurf","replit","created with lovable","built with bolt","generated by ai"];
const AI_FILE_PATTERNS = [".cursorrules",".bolt","lovable.config",".v0",".replit"];

const ghHeaders = () => ({
  Accept: "application/vnd.github.v3+json",
  "User-Agent": "PortfolioForge",
  ...(process.env.GITHUB_TOKEN ? { Authorization: `Bearer ${process.env.GITHUB_TOKEN}` } : {}),
});

async function checkForAIMarkers(username, repoName) {
  try {
    const r = await fetch(`https://api.github.com/repos/${username}/${repoName}/readme`, { headers: ghHeaders() });
    if (r.ok) {
      const d = await r.json();
      if (d.content) {
        const c = Buffer.from(d.content, "base64").toString("utf8").toLowerCase();
        for (const m of AI_TOOL_MARKERS) if (c.includes(m)) return true;
      }
    }
    const r2 = await fetch(`https://api.github.com/repos/${username}/${repoName}/contents`, { headers: ghHeaders() });
    if (r2.ok) {
      const contents = await r2.json();
      if (Array.isArray(contents))
        for (const f of contents)
          for (const p of AI_FILE_PATTERNS)
            if (f.name.toLowerCase().includes(p)) return true;
    }
  } catch {}
  return false;
}

export default async function handler(req, res) {
  res.setHeader("Access-Control-Allow-Origin", "*");
  if (req.method === "OPTIONS") return res.status(200).end();
  if (req.method !== "POST") return res.status(405).json({ error: "Method not allowed" });

  try {
    const { githubUrl } = req.body;
    if (!githubUrl) return res.status(400).json({ error: "Invalid GitHub URL" });
    const match = githubUrl.match(/github\.com\/([^\/\?#]+)/);
    if (!match) return res.status(400).json({ error: "Invalid GitHub URL" });
    const username = match[1];

    const [profileRes, reposRes, eventsRes] = await Promise.all([
      fetch(`https://api.github.com/users/${username}`, { headers: ghHeaders() }),
      fetch(`https://api.github.com/users/${username}/repos?per_page=100&sort=pushed&direction=desc`, { headers: ghHeaders() }),
      fetch(`https://api.github.com/users/${username}/events/public?per_page=100`, { headers: ghHeaders() }),
    ]);

    if (!profileRes.ok) {
      const msg = profileRes.status === 403 ? "GitHub API rate limit exceeded." : profileRes.status === 404 ? `GitHub user not found: ${username}` : `GitHub API error: ${profileRes.status}`;
      return res.status(profileRes.status).json({ error: msg });
    }

    const profile = await profileRes.json();
    const repos = reposRes.ok ? await reposRes.json() : [];
    const events = eventsRes.ok ? await eventsRes.json() : [];

    let pushCount = 0, prCount = 0;
    const collaborations = new Set();
    for (const e of events) {
      if (e.type === "PushEvent") pushCount++;
      if (e.type === "PullRequestEvent") prCount++;
      if (e.repo?.name && !e.repo.name.startsWith(`${username}/`)) collaborations.add(e.repo.name);
    }

    const languageCounts = {};
    let totalStars = 0, ownedRepos = 0, forkedRepos = 0;
    for (const r of repos) {
      if (r.language) languageCounts[r.language] = (languageCounts[r.language] || 0) + (r.stargazers_count + 1);
      totalStars += r.stargazers_count || 0;
      r.fork ? forkedRepos++ : ownedRepos++;
    }
    const totalLangScore = Object.values(languageCounts).reduce((a, b) => a + b, 0) || 1;
    const topLanguages = Object.entries(languageCounts).sort((a, b) => b[1] - a[1]).slice(0, 6)
      .map(([name, score]) => ({ name, percentage: Math.round((score / totalLangScore) * 100) }));

    const topRepos = repos.filter((r) => !r.fork).slice(0, 6);
    const aiResults = await Promise.all(topRepos.map((r) => checkForAIMarkers(username, r.name)));
    const aiDetectedRepos = topRepos.filter((_, i) => aiResults[i]).map((r) => r.name);
    const topProjects = topRepos.map((r, i) => ({
      name: r.name, description: r.description || "No description provided",
      tech: [r.language].filter(Boolean), stars: r.stargazers_count,
      forks: r.forks_count || 0, link: r.html_url, isAiGenerated: aiResults[i],
    }));

    const daysOnGithub = Math.floor((Date.now() - new Date(profile.created_at).getTime()) / 86400000);
    const eventDates = new Set(events.map((e) => new Date(e.created_at).toDateString()));
    let streak = 0;
    for (let i = 0; i < 30; i++) {
      const d = new Date(); d.setDate(d.getDate() - i);
      if (eventDates.has(d.toDateString())) streak++; else if (i > 0) break;
    }
    const recentCommitCount = events.filter((e) => e.type === "PushEvent")
      .reduce((s, e) => s + (e.payload?.commits?.length || 0), 0);

    return res.json({
      name: profile.name || username, title: profile.bio?.split(".")[0] || "Software Developer",
      bio: profile.bio || `Developer based in ${profile.location || "the world"}.`,
      avatar: profile.avatar_url, email: profile.email || `${username}@github.com`,
      location: profile.location || "Earth", github: githubUrl, linkedin: "", website: profile.blog || "",
      skills: [...new Set(repos.filter((r) => r.language).map((r) => r.language))].slice(0, 10),
      projects: topProjects, experience: [], education: [], volunteering: [],
      githubStats: {
        totalCommits: recentCommitCount > 0 ? recentCommitCount : profile.public_repos * 15,
        publicRepos: profile.public_repos, privateRepos: profile.total_private_repos || 0,
        ownedRepos, forkedRepos, followers: profile.followers, following: profile.following,
        totalStars, pullRequests: prCount, pushes: pushCount, daysOnGithub,
        recentCollaborations: [...collaborations].slice(0, 5),
        aiGeneratedContent: aiDetectedRepos.length, aiDetectedRepos, topLanguages,
        contributionStreak: streak, accountCreated: profile.created_at,
        lastActive: events[0]?.created_at || profile.updated_at,
      },
    });
  } catch (e) {
    return res.status(500).json({ error: e.message || "Unknown error" });
  }
}
